trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Global Infra'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(serviceConnectionName)'
      subscriptionId: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'ProjectFtk-Trial'
      location: 'West US'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Global/Global.json'
      csmParametersFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Global/Global.Parameters.json'
      deploymentMode: 'Incremental'