trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: regions
  type: object
  default: ['Central US']
- name: globalRegion
  type: string
  default: 'Central US'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Global Infra'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(serviceConnectionName)'
      subscriptionId: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'ProjectFtk-Global'
      location: '${{ parameters.globalRegion }}'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Global/Global.json'
      csmParametersFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Global/Global.Parameters.json'
      deploymentMode: 'Incremental'
  - ${{ each region in parameters.regions }}:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ${{ region }} Infra'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(serviceConnectionName)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ replace({{region}}, ' ', '_') }}
        location: '${{ region }}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Regional/Regional.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Deployment/ARM/Regional/Regional.Parameters.json'
        deploymentMode: 'Incremental'