trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  regions : ['westus']
  globalRegion: 'westus'

steps:
  - task: AzurePowerShell@5
    displayName: 'Deploy Global Infra'
    inputs:
      azureSubscription: '$(serviceConnectionName)'
      ScriptType: 'FilePath'
      ScriptPath: './Deploy-AzTemplate.ps1'
      ScriptArguments: -Location '${{ region }}' -ResourceGroupName 'ProjectFtk-${{ region }}' -TemplateFile ARM/Regional/Regional.json -TemplateParameterFile ARM/Regional/Regional.Parameters.json
      azurePowerShellVersion: 'LatestVersion'
- ${{ each region in parameters.regions }}:
  - task: AzurePowerShell@5
    displayName: 'Deploy ${{ region }} Infra'
    inputs:
      azureSubscription: '$(serviceConnectionName)'
      ScriptType: 'FilePath'
      ScriptPath: './Deploy-AzTemplate.ps1'
      ScriptArguments: -Location '${{ region }}' -ResourceGroupName 'ProjectFtk-${{ region }}' -TemplateFile ARM/Regional/Regional.json -TemplateParameterFile ARM/Regional/Regional.Parameters.json
      azurePowerShellVersion: 'LatestVersion'